version: 1
genesis:
  chain_id: testnet-ghostcloud-001
accounts:
- name: alice
  coins:
  - 20000token
  - 200000000stake
- name: bob
  coins:
  - 10000token
  - 100000000stake
- name: faucet
  coins:
    - 10000token
client:
  openapi:
    path: docs/static/openapi.yml
# The following faucet parameters are only used when running `ignite chain serve` locally.
# Testnets/mainnets should use a separate faucet service.
faucet:
  name: faucet
  coins:
    - 50token
  coins_max:
    - 100token
  rate_limit_window: 3600s
validators:
- name: alice
  bonded: 100000000stake
  config:
    rpc:
      max_body_bytes: "10485760"
    mempool:
      max_txs_bytes: "5368709120"
      max_tx_bytes: "5242880"
