# ghostcloud-cosmos CI
# The Lifted Initiative
version: 2.1

orbs:
  go: circleci/go@1.9.0
  codecov: codecov/codecov@3.3.0

jobs:
  build:
    executor:
      name: go/default
      tag: '1.19'
    steps:
      - checkout
      - go/load-cache
      - go/mod-download
      - go/save-cache
      - run: make coverage
      - codecov/upload:
          file: coverage-filtered.out
workflows:
  main:
    jobs:
      - build
